/* Auto-generated by snesrecomp v2 tools/v2_sync_funcs_h.py.
 * Do NOT hand-edit. Every recompiled function takes a
 * CpuState* and mutates it in place — no return values, no
 * register-packed structs. Drop custom typedefs (HdmaPtrs,
 * PairU8, OwHvPos, CollInfo, ExtCollOut, CheckPlatformCollRet,
 * CalcTiltPlatformArgs) — all v1 ABI fiction, gone.
 *
 * Per-(m, x) variants: every named function is declared in
 * five forms so cross-bank generated calls can reference any
 * variant without a side-car header dependency. Unused
 * variants are harmless (C only flags undefined REFERENCES,
 * not undefined DECLARATIONS at link time).
 */
#pragma once

#include "cpu_state.h"

/* 126 functions across all banks (5 decls each). */

void bank_00_8000(CpuState *cpu);  /* $00:8000 alias */
RecompReturn bank_00_8000_M0X0(CpuState *cpu);
RecompReturn bank_00_8000_M0X1(CpuState *cpu);
RecompReturn bank_00_8000_M1X0(CpuState *cpu);
RecompReturn bank_00_8000_M1X1(CpuState *cpu);
void bank_00_808C(CpuState *cpu);  /* $00:808C alias */
RecompReturn bank_00_808C_M0X0(CpuState *cpu);
RecompReturn bank_00_808C_M0X1(CpuState *cpu);
RecompReturn bank_00_808C_M1X0(CpuState *cpu);
RecompReturn bank_00_808C_M1X1(CpuState *cpu);
void bank_00_80D9(CpuState *cpu);  /* $00:80D9 alias */
RecompReturn bank_00_80D9_M0X0(CpuState *cpu);
RecompReturn bank_00_80D9_M0X1(CpuState *cpu);
RecompReturn bank_00_80D9_M1X0(CpuState *cpu);
RecompReturn bank_00_80D9_M1X1(CpuState *cpu);
void bank_00_8139(CpuState *cpu);  /* $00:8139 alias */
RecompReturn bank_00_8139_M0X0(CpuState *cpu);
RecompReturn bank_00_8139_M0X1(CpuState *cpu);
RecompReturn bank_00_8139_M1X0(CpuState *cpu);
RecompReturn bank_00_8139_M1X1(CpuState *cpu);
void bank_00_8140(CpuState *cpu);  /* $00:8140 alias */
RecompReturn bank_00_8140_M0X0(CpuState *cpu);
RecompReturn bank_00_8140_M0X1(CpuState *cpu);
RecompReturn bank_00_8140_M1X0(CpuState *cpu);
RecompReturn bank_00_8140_M1X1(CpuState *cpu);
void bank_00_81AC(CpuState *cpu);  /* $00:81AC alias */
RecompReturn bank_00_81AC_M0X0(CpuState *cpu);
RecompReturn bank_00_81AC_M0X1(CpuState *cpu);
RecompReturn bank_00_81AC_M1X0(CpuState *cpu);
RecompReturn bank_00_81AC_M1X1(CpuState *cpu);
void bank_00_824F(CpuState *cpu);  /* $00:824F alias */
RecompReturn bank_00_824F_M0X0(CpuState *cpu);
RecompReturn bank_00_824F_M0X1(CpuState *cpu);
RecompReturn bank_00_824F_M1X0(CpuState *cpu);
RecompReturn bank_00_824F_M1X1(CpuState *cpu);
void bank_00_829B(CpuState *cpu);  /* $00:829B alias */
RecompReturn bank_00_829B_M0X0(CpuState *cpu);
RecompReturn bank_00_829B_M0X1(CpuState *cpu);
RecompReturn bank_00_829B_M1X0(CpuState *cpu);
RecompReturn bank_00_829B_M1X1(CpuState *cpu);
void bank_00_8364(CpuState *cpu);  /* $00:8364 alias */
RecompReturn bank_00_8364_M0X0(CpuState *cpu);
RecompReturn bank_00_8364_M0X1(CpuState *cpu);
RecompReturn bank_00_8364_M1X0(CpuState *cpu);
RecompReturn bank_00_8364_M1X1(CpuState *cpu);
void bank_00_83B5(CpuState *cpu);  /* $00:83B5 alias */
RecompReturn bank_00_83B5_M0X0(CpuState *cpu);
RecompReturn bank_00_83B5_M0X1(CpuState *cpu);
RecompReturn bank_00_83B5_M1X0(CpuState *cpu);
RecompReturn bank_00_83B5_M1X1(CpuState *cpu);
void bank_00_840A(CpuState *cpu);  /* $00:840A alias */
RecompReturn bank_00_840A_M0X0(CpuState *cpu);
RecompReturn bank_00_840A_M0X1(CpuState *cpu);
RecompReturn bank_00_840A_M1X0(CpuState *cpu);
RecompReturn bank_00_840A_M1X1(CpuState *cpu);
void bank_00_8470(CpuState *cpu);  /* $00:8470 alias */
RecompReturn bank_00_8470_M0X0(CpuState *cpu);
RecompReturn bank_00_8470_M0X1(CpuState *cpu);
RecompReturn bank_00_8470_M1X0(CpuState *cpu);
RecompReturn bank_00_8470_M1X1(CpuState *cpu);
void bank_00_84E0(CpuState *cpu);  /* $00:84E0 alias */
RecompReturn bank_00_84E0_M0X0(CpuState *cpu);
RecompReturn bank_00_84E0_M0X1(CpuState *cpu);
RecompReturn bank_00_84E0_M1X0(CpuState *cpu);
RecompReturn bank_00_84E0_M1X1(CpuState *cpu);
void bank_00_8601(CpuState *cpu);  /* $00:8601 alias */
RecompReturn bank_00_8601_M0X0(CpuState *cpu);
RecompReturn bank_00_8601_M0X1(CpuState *cpu);
RecompReturn bank_00_8601_M1X0(CpuState *cpu);
RecompReturn bank_00_8601_M1X1(CpuState *cpu);
void bank_00_86FB(CpuState *cpu);  /* $00:86FB alias */
RecompReturn bank_00_86FB_M0X0(CpuState *cpu);
RecompReturn bank_00_86FB_M0X1(CpuState *cpu);
RecompReturn bank_00_86FB_M1X0(CpuState *cpu);
RecompReturn bank_00_86FB_M1X1(CpuState *cpu);
void bank_00_876A(CpuState *cpu);  /* $00:876A alias */
RecompReturn bank_00_876A_M0X0(CpuState *cpu);
RecompReturn bank_00_876A_M0X1(CpuState *cpu);
RecompReturn bank_00_876A_M1X0(CpuState *cpu);
RecompReturn bank_00_876A_M1X1(CpuState *cpu);
void bank_00_876E(CpuState *cpu);  /* $00:876E alias */
RecompReturn bank_00_876E_M0X0(CpuState *cpu);
RecompReturn bank_00_876E_M0X1(CpuState *cpu);
RecompReturn bank_00_876E_M1X0(CpuState *cpu);
RecompReturn bank_00_876E_M1X1(CpuState *cpu);
void bank_00_8772(CpuState *cpu);  /* $00:8772 alias */
RecompReturn bank_00_8772_M0X0(CpuState *cpu);
RecompReturn bank_00_8772_M0X1(CpuState *cpu);
RecompReturn bank_00_8772_M1X0(CpuState *cpu);
RecompReturn bank_00_8772_M1X1(CpuState *cpu);
void bank_00_8776(CpuState *cpu);  /* $00:8776 alias */
RecompReturn bank_00_8776_M0X0(CpuState *cpu);
RecompReturn bank_00_8776_M0X1(CpuState *cpu);
RecompReturn bank_00_8776_M1X0(CpuState *cpu);
RecompReturn bank_00_8776_M1X1(CpuState *cpu);
void bank_00_877A(CpuState *cpu);  /* $00:877A alias */
RecompReturn bank_00_877A_M0X0(CpuState *cpu);
RecompReturn bank_00_877A_M0X1(CpuState *cpu);
RecompReturn bank_00_877A_M1X0(CpuState *cpu);
RecompReturn bank_00_877A_M1X1(CpuState *cpu);
void bank_00_877E(CpuState *cpu);  /* $00:877E alias */
RecompReturn bank_00_877E_M0X0(CpuState *cpu);
RecompReturn bank_00_877E_M0X1(CpuState *cpu);
RecompReturn bank_00_877E_M1X0(CpuState *cpu);
RecompReturn bank_00_877E_M1X1(CpuState *cpu);
void bank_00_8782(CpuState *cpu);  /* $00:8782 alias */
RecompReturn bank_00_8782_M0X0(CpuState *cpu);
RecompReturn bank_00_8782_M0X1(CpuState *cpu);
RecompReturn bank_00_8782_M1X0(CpuState *cpu);
RecompReturn bank_00_8782_M1X1(CpuState *cpu);
void bank_00_8892(CpuState *cpu);  /* $00:8892 alias */
RecompReturn bank_00_8892_M0X0(CpuState *cpu);
RecompReturn bank_00_8892_M0X1(CpuState *cpu);
RecompReturn bank_00_8892_M1X0(CpuState *cpu);
RecompReturn bank_00_8892_M1X1(CpuState *cpu);
void bank_00_89C4(CpuState *cpu);  /* $00:89C4 alias */
RecompReturn bank_00_89C4_M0X0(CpuState *cpu);
RecompReturn bank_00_89C4_M0X1(CpuState *cpu);
RecompReturn bank_00_89C4_M1X0(CpuState *cpu);
RecompReturn bank_00_89C4_M1X1(CpuState *cpu);
void bank_00_8ACD(CpuState *cpu);  /* $00:8ACD alias */
RecompReturn bank_00_8ACD_M0X0(CpuState *cpu);
RecompReturn bank_00_8ACD_M0X1(CpuState *cpu);
RecompReturn bank_00_8ACD_M1X0(CpuState *cpu);
RecompReturn bank_00_8ACD_M1X1(CpuState *cpu);
void bank_00_9002(CpuState *cpu);  /* $00:9002 alias */
RecompReturn bank_00_9002_M0X0(CpuState *cpu);
RecompReturn bank_00_9002_M0X1(CpuState *cpu);
RecompReturn bank_00_9002_M1X0(CpuState *cpu);
RecompReturn bank_00_9002_M1X1(CpuState *cpu);
void bank_00_94F0(CpuState *cpu);  /* $00:94F0 alias */
RecompReturn bank_00_94F0_M0X0(CpuState *cpu);
RecompReturn bank_00_94F0_M0X1(CpuState *cpu);
RecompReturn bank_00_94F0_M1X0(CpuState *cpu);
RecompReturn bank_00_94F0_M1X1(CpuState *cpu);
void bank_00_953A(CpuState *cpu);  /* $00:953A alias */
RecompReturn bank_00_953A_M0X0(CpuState *cpu);
RecompReturn bank_00_953A_M0X1(CpuState *cpu);
RecompReturn bank_00_953A_M1X0(CpuState *cpu);
RecompReturn bank_00_953A_M1X1(CpuState *cpu);
void bank_00_9589(CpuState *cpu);  /* $00:9589 alias */
RecompReturn bank_00_9589_M0X0(CpuState *cpu);
RecompReturn bank_00_9589_M0X1(CpuState *cpu);
RecompReturn bank_00_9589_M1X0(CpuState *cpu);
RecompReturn bank_00_9589_M1X1(CpuState *cpu);
void bank_00_96F2(CpuState *cpu);  /* $00:96F2 alias */
RecompReturn bank_00_96F2_M0X0(CpuState *cpu);
RecompReturn bank_00_96F2_M0X1(CpuState *cpu);
RecompReturn bank_00_96F2_M1X0(CpuState *cpu);
RecompReturn bank_00_96F2_M1X1(CpuState *cpu);
void bank_00_9753(CpuState *cpu);  /* $00:9753 alias */
RecompReturn bank_00_9753_M0X0(CpuState *cpu);
RecompReturn bank_00_9753_M0X1(CpuState *cpu);
RecompReturn bank_00_9753_M1X0(CpuState *cpu);
RecompReturn bank_00_9753_M1X1(CpuState *cpu);
void bank_00_97BC(CpuState *cpu);  /* $00:97BC alias */
RecompReturn bank_00_97BC_M0X0(CpuState *cpu);
RecompReturn bank_00_97BC_M0X1(CpuState *cpu);
RecompReturn bank_00_97BC_M1X0(CpuState *cpu);
RecompReturn bank_00_97BC_M1X1(CpuState *cpu);
void bank_00_97E3(CpuState *cpu);  /* $00:97E3 alias */
RecompReturn bank_00_97E3_M0X0(CpuState *cpu);
RecompReturn bank_00_97E3_M0X1(CpuState *cpu);
RecompReturn bank_00_97E3_M1X0(CpuState *cpu);
RecompReturn bank_00_97E3_M1X1(CpuState *cpu);
void bank_00_9D42(CpuState *cpu);  /* $00:9D42 alias */
RecompReturn bank_00_9D42_M0X0(CpuState *cpu);
RecompReturn bank_00_9D42_M0X1(CpuState *cpu);
RecompReturn bank_00_9D42_M1X0(CpuState *cpu);
RecompReturn bank_00_9D42_M1X1(CpuState *cpu);
void bank_00_9EAB(CpuState *cpu);  /* $00:9EAB alias */
RecompReturn bank_00_9EAB_M0X0(CpuState *cpu);
RecompReturn bank_00_9EAB_M0X1(CpuState *cpu);
RecompReturn bank_00_9EAB_M1X0(CpuState *cpu);
RecompReturn bank_00_9EAB_M1X1(CpuState *cpu);
void bank_00_9EE0(CpuState *cpu);  /* $00:9EE0 alias */
RecompReturn bank_00_9EE0_M0X0(CpuState *cpu);
RecompReturn bank_00_9EE0_M0X1(CpuState *cpu);
RecompReturn bank_00_9EE0_M1X0(CpuState *cpu);
RecompReturn bank_00_9EE0_M1X1(CpuState *cpu);
void bank_00_9EE4(CpuState *cpu);  /* $00:9EE4 alias */
RecompReturn bank_00_9EE4_M0X0(CpuState *cpu);
RecompReturn bank_00_9EE4_M0X1(CpuState *cpu);
RecompReturn bank_00_9EE4_M1X0(CpuState *cpu);
RecompReturn bank_00_9EE4_M1X1(CpuState *cpu);
void bank_00_9EE8(CpuState *cpu);  /* $00:9EE8 alias */
RecompReturn bank_00_9EE8_M0X0(CpuState *cpu);
RecompReturn bank_00_9EE8_M0X1(CpuState *cpu);
RecompReturn bank_00_9EE8_M1X0(CpuState *cpu);
RecompReturn bank_00_9EE8_M1X1(CpuState *cpu);
void bank_00_9EEC(CpuState *cpu);  /* $00:9EEC alias */
RecompReturn bank_00_9EEC_M0X0(CpuState *cpu);
RecompReturn bank_00_9EEC_M0X1(CpuState *cpu);
RecompReturn bank_00_9EEC_M1X0(CpuState *cpu);
RecompReturn bank_00_9EEC_M1X1(CpuState *cpu);
void bank_00_9EF0(CpuState *cpu);  /* $00:9EF0 alias */
RecompReturn bank_00_9EF0_M0X0(CpuState *cpu);
RecompReturn bank_00_9EF0_M0X1(CpuState *cpu);
RecompReturn bank_00_9EF0_M1X0(CpuState *cpu);
RecompReturn bank_00_9EF0_M1X1(CpuState *cpu);
void bank_00_9EF4(CpuState *cpu);  /* $00:9EF4 alias */
RecompReturn bank_00_9EF4_M0X0(CpuState *cpu);
RecompReturn bank_00_9EF4_M0X1(CpuState *cpu);
RecompReturn bank_00_9EF4_M1X0(CpuState *cpu);
RecompReturn bank_00_9EF4_M1X1(CpuState *cpu);
void bank_00_9EF8(CpuState *cpu);  /* $00:9EF8 alias */
RecompReturn bank_00_9EF8_M0X0(CpuState *cpu);
RecompReturn bank_00_9EF8_M0X1(CpuState *cpu);
RecompReturn bank_00_9EF8_M1X0(CpuState *cpu);
RecompReturn bank_00_9EF8_M1X1(CpuState *cpu);
void bank_00_9EFC(CpuState *cpu);  /* $00:9EFC alias */
RecompReturn bank_00_9EFC_M0X0(CpuState *cpu);
RecompReturn bank_00_9EFC_M0X1(CpuState *cpu);
RecompReturn bank_00_9EFC_M1X0(CpuState *cpu);
RecompReturn bank_00_9EFC_M1X1(CpuState *cpu);
void bank_00_A1C0(CpuState *cpu);  /* $00:A1C0 alias */
RecompReturn bank_00_A1C0_M0X0(CpuState *cpu);
RecompReturn bank_00_A1C0_M0X1(CpuState *cpu);
RecompReturn bank_00_A1C0_M1X0(CpuState *cpu);
RecompReturn bank_00_A1C0_M1X1(CpuState *cpu);
void bank_00_A1E5(CpuState *cpu);  /* $00:A1E5 alias */
RecompReturn bank_00_A1E5_M0X0(CpuState *cpu);
RecompReturn bank_00_A1E5_M0X1(CpuState *cpu);
RecompReturn bank_00_A1E5_M1X0(CpuState *cpu);
RecompReturn bank_00_A1E5_M1X1(CpuState *cpu);
void bank_00_A23D(CpuState *cpu);  /* $00:A23D alias */
RecompReturn bank_00_A23D_M0X0(CpuState *cpu);
RecompReturn bank_00_A23D_M0X1(CpuState *cpu);
RecompReturn bank_00_A23D_M1X0(CpuState *cpu);
RecompReturn bank_00_A23D_M1X1(CpuState *cpu);
void bank_00_A30D(CpuState *cpu);  /* $00:A30D alias */
RecompReturn bank_00_A30D_M0X0(CpuState *cpu);
RecompReturn bank_00_A30D_M0X1(CpuState *cpu);
RecompReturn bank_00_A30D_M1X0(CpuState *cpu);
RecompReturn bank_00_A30D_M1X1(CpuState *cpu);
void bank_00_A38B(CpuState *cpu);  /* $00:A38B alias */
RecompReturn bank_00_A38B_M0X0(CpuState *cpu);
RecompReturn bank_00_A38B_M0X1(CpuState *cpu);
RecompReturn bank_00_A38B_M1X0(CpuState *cpu);
RecompReturn bank_00_A38B_M1X1(CpuState *cpu);
void bank_00_A807(CpuState *cpu);  /* $00:A807 alias */
RecompReturn bank_00_A807_M0X0(CpuState *cpu);
RecompReturn bank_00_A807_M0X1(CpuState *cpu);
RecompReturn bank_00_A807_M1X0(CpuState *cpu);
RecompReturn bank_00_A807_M1X1(CpuState *cpu);
void bank_00_AA35(CpuState *cpu);  /* $00:AA35 alias */
RecompReturn bank_00_AA35_M0X0(CpuState *cpu);
RecompReturn bank_00_AA35_M0X1(CpuState *cpu);
RecompReturn bank_00_AA35_M1X0(CpuState *cpu);
RecompReturn bank_00_AA35_M1X1(CpuState *cpu);
void bank_00_AB00(CpuState *cpu);  /* $00:AB00 alias */
RecompReturn bank_00_AB00_M0X0(CpuState *cpu);
RecompReturn bank_00_AB00_M0X1(CpuState *cpu);
RecompReturn bank_00_AB00_M1X0(CpuState *cpu);
RecompReturn bank_00_AB00_M1X1(CpuState *cpu);
void bank_00_AB03(CpuState *cpu);  /* $00:AB03 alias */
RecompReturn bank_00_AB03_M0X0(CpuState *cpu);
RecompReturn bank_00_AB03_M0X1(CpuState *cpu);
RecompReturn bank_00_AB03_M1X0(CpuState *cpu);
RecompReturn bank_00_AB03_M1X1(CpuState *cpu);
void bank_00_AB79(CpuState *cpu);  /* $00:AB79 alias */
RecompReturn bank_00_AB79_M0X0(CpuState *cpu);
RecompReturn bank_00_AB79_M0X1(CpuState *cpu);
RecompReturn bank_00_AB79_M1X0(CpuState *cpu);
RecompReturn bank_00_AB79_M1X1(CpuState *cpu);
void bank_00_AC2D(CpuState *cpu);  /* $00:AC2D alias */
RecompReturn bank_00_AC2D_M0X0(CpuState *cpu);
RecompReturn bank_00_AC2D_M0X1(CpuState *cpu);
RecompReturn bank_00_AC2D_M1X0(CpuState *cpu);
RecompReturn bank_00_AC2D_M1X1(CpuState *cpu);
void bank_00_AD18(CpuState *cpu);  /* $00:AD18 alias */
RecompReturn bank_00_AD18_M0X0(CpuState *cpu);
RecompReturn bank_00_AD18_M0X1(CpuState *cpu);
RecompReturn bank_00_AD18_M1X0(CpuState *cpu);
RecompReturn bank_00_AD18_M1X1(CpuState *cpu);
void bank_00_AD35(CpuState *cpu);  /* $00:AD35 alias */
RecompReturn bank_00_AD35_M0X0(CpuState *cpu);
RecompReturn bank_00_AD35_M0X1(CpuState *cpu);
RecompReturn bank_00_AD35_M1X0(CpuState *cpu);
RecompReturn bank_00_AD35_M1X1(CpuState *cpu);
void bank_00_AF58(CpuState *cpu);  /* $00:AF58 alias */
RecompReturn bank_00_AF58_M0X0(CpuState *cpu);
RecompReturn bank_00_AF58_M0X1(CpuState *cpu);
RecompReturn bank_00_AF58_M1X0(CpuState *cpu);
RecompReturn bank_00_AF58_M1X1(CpuState *cpu);
void bank_00_AF91(CpuState *cpu);  /* $00:AF91 alias */
RecompReturn bank_00_AF91_M0X0(CpuState *cpu);
RecompReturn bank_00_AF91_M0X1(CpuState *cpu);
RecompReturn bank_00_AF91_M1X0(CpuState *cpu);
RecompReturn bank_00_AF91_M1X1(CpuState *cpu);
void bank_00_B0C8(CpuState *cpu);  /* $00:B0C8 alias */
RecompReturn bank_00_B0C8_M0X0(CpuState *cpu);
RecompReturn bank_00_B0C8_M0X1(CpuState *cpu);
RecompReturn bank_00_B0C8_M1X0(CpuState *cpu);
RecompReturn bank_00_B0C8_M1X1(CpuState *cpu);
void bank_00_B0DD(CpuState *cpu);  /* $00:B0DD alias */
RecompReturn bank_00_B0DD_M0X0(CpuState *cpu);
RecompReturn bank_00_B0DD_M0X1(CpuState *cpu);
RecompReturn bank_00_B0DD_M1X0(CpuState *cpu);
RecompReturn bank_00_B0DD_M1X1(CpuState *cpu);
void bank_00_B125(CpuState *cpu);  /* $00:B125 alias */
RecompReturn bank_00_B125_M0X0(CpuState *cpu);
RecompReturn bank_00_B125_M0X1(CpuState *cpu);
RecompReturn bank_00_B125_M1X0(CpuState *cpu);
RecompReturn bank_00_B125_M1X1(CpuState *cpu);
void bank_00_BE45(CpuState *cpu);  /* $00:BE45 alias */
RecompReturn bank_00_BE45_M0X0(CpuState *cpu);
RecompReturn bank_00_BE45_M0X1(CpuState *cpu);
RecompReturn bank_00_BE45_M1X0(CpuState *cpu);
RecompReturn bank_00_BE45_M1X1(CpuState *cpu);
void bank_00_C07E(CpuState *cpu);  /* $00:C07E alias */
RecompReturn bank_00_C07E_M0X0(CpuState *cpu);
RecompReturn bank_00_C07E_M0X1(CpuState *cpu);
RecompReturn bank_00_C07E_M1X0(CpuState *cpu);
RecompReturn bank_00_C07E_M1X1(CpuState *cpu);
void bank_00_C095(CpuState *cpu);  /* $00:C095 alias */
RecompReturn bank_00_C095_M0X0(CpuState *cpu);
RecompReturn bank_00_C095_M0X1(CpuState *cpu);
RecompReturn bank_00_C095_M1X0(CpuState *cpu);
RecompReturn bank_00_C095_M1X1(CpuState *cpu);
void bank_00_C152(CpuState *cpu);  /* $00:C152 alias */
RecompReturn bank_00_C152_M0X0(CpuState *cpu);
RecompReturn bank_00_C152_M0X1(CpuState *cpu);
RecompReturn bank_00_C152_M1X0(CpuState *cpu);
RecompReturn bank_00_C152_M1X1(CpuState *cpu);
void bank_00_C2ED(CpuState *cpu);  /* $00:C2ED alias */
RecompReturn bank_00_C2ED_M0X0(CpuState *cpu);
RecompReturn bank_00_C2ED_M0X1(CpuState *cpu);
RecompReturn bank_00_C2ED_M1X0(CpuState *cpu);
RecompReturn bank_00_C2ED_M1X1(CpuState *cpu);
void bank_00_C30D(CpuState *cpu);  /* $00:C30D alias */
RecompReturn bank_00_C30D_M0X0(CpuState *cpu);
RecompReturn bank_00_C30D_M0X1(CpuState *cpu);
RecompReturn bank_00_C30D_M1X0(CpuState *cpu);
RecompReturn bank_00_C30D_M1X1(CpuState *cpu);
void bank_00_C735(CpuState *cpu);  /* $00:C735 alias */
RecompReturn bank_00_C735_M0X0(CpuState *cpu);
RecompReturn bank_00_C735_M0X1(CpuState *cpu);
RecompReturn bank_00_C735_M1X0(CpuState *cpu);
RecompReturn bank_00_C735_M1X1(CpuState *cpu);
void bank_00_C90A(CpuState *cpu);  /* $00:C90A alias */
RecompReturn bank_00_C90A_M0X0(CpuState *cpu);
RecompReturn bank_00_C90A_M0X1(CpuState *cpu);
RecompReturn bank_00_C90A_M1X0(CpuState *cpu);
RecompReturn bank_00_C90A_M1X1(CpuState *cpu);
void bank_00_C9C0(CpuState *cpu);  /* $00:C9C0 alias */
RecompReturn bank_00_C9C0_M0X0(CpuState *cpu);
RecompReturn bank_00_C9C0_M0X1(CpuState *cpu);
RecompReturn bank_00_C9C0_M1X0(CpuState *cpu);
RecompReturn bank_00_C9C0_M1X1(CpuState *cpu);
void bank_00_D0AA(CpuState *cpu);  /* $00:D0AA alias */
RecompReturn bank_00_D0AA_M0X0(CpuState *cpu);
RecompReturn bank_00_D0AA_M0X1(CpuState *cpu);
RecompReturn bank_00_D0AA_M1X0(CpuState *cpu);
RecompReturn bank_00_D0AA_M1X1(CpuState *cpu);
void bank_00_D193(CpuState *cpu);  /* $00:D193 alias */
RecompReturn bank_00_D193_M0X0(CpuState *cpu);
RecompReturn bank_00_D193_M0X1(CpuState *cpu);
RecompReturn bank_00_D193_M1X0(CpuState *cpu);
RecompReturn bank_00_D193_M1X1(CpuState *cpu);
void bank_00_D1D5(CpuState *cpu);  /* $00:D1D5 alias */
RecompReturn bank_00_D1D5_M0X0(CpuState *cpu);
RecompReturn bank_00_D1D5_M0X1(CpuState *cpu);
RecompReturn bank_00_D1D5_M1X0(CpuState *cpu);
RecompReturn bank_00_D1D5_M1X1(CpuState *cpu);
void bank_00_D1F0(CpuState *cpu);  /* $00:D1F0 alias */
RecompReturn bank_00_D1F0_M0X0(CpuState *cpu);
RecompReturn bank_00_D1F0_M0X1(CpuState *cpu);
RecompReturn bank_00_D1F0_M1X0(CpuState *cpu);
RecompReturn bank_00_D1F0_M1X1(CpuState *cpu);
void bank_00_D2CF(CpuState *cpu);  /* $00:D2CF alias */
RecompReturn bank_00_D2CF_M0X0(CpuState *cpu);
RecompReturn bank_00_D2CF_M0X1(CpuState *cpu);
RecompReturn bank_00_D2CF_M1X0(CpuState *cpu);
RecompReturn bank_00_D2CF_M1X1(CpuState *cpu);
void bank_00_D71D(CpuState *cpu);  /* $00:D71D alias */
RecompReturn bank_00_D71D_M0X0(CpuState *cpu);
RecompReturn bank_00_D71D_M0X1(CpuState *cpu);
RecompReturn bank_00_D71D_M1X0(CpuState *cpu);
RecompReturn bank_00_D71D_M1X1(CpuState *cpu);
void bank_00_D86E(CpuState *cpu);  /* $00:D86E alias */
RecompReturn bank_00_D86E_M0X0(CpuState *cpu);
RecompReturn bank_00_D86E_M0X1(CpuState *cpu);
RecompReturn bank_00_D86E_M1X0(CpuState *cpu);
RecompReturn bank_00_D86E_M1X1(CpuState *cpu);
void bank_00_D8A3(CpuState *cpu);  /* $00:D8A3 alias */
RecompReturn bank_00_D8A3_M0X0(CpuState *cpu);
RecompReturn bank_00_D8A3_M0X1(CpuState *cpu);
RecompReturn bank_00_D8A3_M1X0(CpuState *cpu);
RecompReturn bank_00_D8A3_M1X1(CpuState *cpu);
void bank_00_E5CF(CpuState *cpu);  /* $00:E5CF alias */
RecompReturn bank_00_E5CF_M0X0(CpuState *cpu);
RecompReturn bank_00_E5CF_M0X1(CpuState *cpu);
RecompReturn bank_00_E5CF_M1X0(CpuState *cpu);
RecompReturn bank_00_E5CF_M1X1(CpuState *cpu);
void bank_00_E778(CpuState *cpu);  /* $00:E778 alias */
RecompReturn bank_00_E778_M0X0(CpuState *cpu);
RecompReturn bank_00_E778_M0X1(CpuState *cpu);
RecompReturn bank_00_E778_M1X0(CpuState *cpu);
RecompReturn bank_00_E778_M1X1(CpuState *cpu);
void bank_00_EA56(CpuState *cpu);  /* $00:EA56 alias */
RecompReturn bank_00_EA56_M0X0(CpuState *cpu);
RecompReturn bank_00_EA56_M0X1(CpuState *cpu);
RecompReturn bank_00_EA56_M1X0(CpuState *cpu);
RecompReturn bank_00_EA56_M1X1(CpuState *cpu);
void bank_00_F28B(CpuState *cpu);  /* $00:F28B alias */
RecompReturn bank_00_F28B_M0X0(CpuState *cpu);
RecompReturn bank_00_F28B_M0X1(CpuState *cpu);
RecompReturn bank_00_F28B_M1X0(CpuState *cpu);
RecompReturn bank_00_F28B_M1X1(CpuState *cpu);
void bank_00_F67A(CpuState *cpu);  /* $00:F67A alias */
RecompReturn bank_00_F67A_M0X0(CpuState *cpu);
RecompReturn bank_00_F67A_M0X1(CpuState *cpu);
RecompReturn bank_00_F67A_M1X0(CpuState *cpu);
RecompReturn bank_00_F67A_M1X1(CpuState *cpu);
void bank_00_F6FB(CpuState *cpu);  /* $00:F6FB alias */
RecompReturn bank_00_F6FB_M0X0(CpuState *cpu);
RecompReturn bank_00_F6FB_M0X1(CpuState *cpu);
RecompReturn bank_00_F6FB_M1X0(CpuState *cpu);
RecompReturn bank_00_F6FB_M1X1(CpuState *cpu);
void bank_00_F70D(CpuState *cpu);  /* $00:F70D alias */
RecompReturn bank_00_F70D_M0X0(CpuState *cpu);
RecompReturn bank_00_F70D_M0X1(CpuState *cpu);
RecompReturn bank_00_F70D_M1X0(CpuState *cpu);
RecompReturn bank_00_F70D_M1X1(CpuState *cpu);
void bank_00_F738(CpuState *cpu);  /* $00:F738 alias */
RecompReturn bank_00_F738_M0X0(CpuState *cpu);
RecompReturn bank_00_F738_M0X1(CpuState *cpu);
RecompReturn bank_00_F738_M1X0(CpuState *cpu);
RecompReturn bank_00_F738_M1X1(CpuState *cpu);
void bank_00_F778(CpuState *cpu);  /* $00:F778 alias */
RecompReturn bank_00_F778_M0X0(CpuState *cpu);
RecompReturn bank_00_F778_M0X1(CpuState *cpu);
RecompReturn bank_00_F778_M1X0(CpuState *cpu);
RecompReturn bank_00_F778_M1X1(CpuState *cpu);
void bank_00_F8C6(CpuState *cpu);  /* $00:F8C6 alias */
RecompReturn bank_00_F8C6_M0X0(CpuState *cpu);
RecompReturn bank_00_F8C6_M0X1(CpuState *cpu);
RecompReturn bank_00_F8C6_M1X0(CpuState *cpu);
RecompReturn bank_00_F8C6_M1X1(CpuState *cpu);
void bank_00_F8DD(CpuState *cpu);  /* $00:F8DD alias */
RecompReturn bank_00_F8DD_M0X0(CpuState *cpu);
RecompReturn bank_00_F8DD_M0X1(CpuState *cpu);
RecompReturn bank_00_F8DD_M1X0(CpuState *cpu);
RecompReturn bank_00_F8DD_M1X1(CpuState *cpu);
void bank_02_C3C6(CpuState *cpu);  /* $02:C3C6 alias */
RecompReturn bank_02_C3C6_M0X0(CpuState *cpu);
RecompReturn bank_02_C3C6_M0X1(CpuState *cpu);
RecompReturn bank_02_C3C6_M1X0(CpuState *cpu);
RecompReturn bank_02_C3C6_M1X1(CpuState *cpu);
void bank_02_C47D(CpuState *cpu);  /* $02:C47D alias */
RecompReturn bank_02_C47D_M0X0(CpuState *cpu);
RecompReturn bank_02_C47D_M0X1(CpuState *cpu);
RecompReturn bank_02_C47D_M1X0(CpuState *cpu);
RecompReturn bank_02_C47D_M1X1(CpuState *cpu);
void bank_02_C49F(CpuState *cpu);  /* $02:C49F alias */
RecompReturn bank_02_C49F_M0X0(CpuState *cpu);
RecompReturn bank_02_C49F_M0X1(CpuState *cpu);
RecompReturn bank_02_C49F_M1X0(CpuState *cpu);
RecompReturn bank_02_C49F_M1X1(CpuState *cpu);
void bank_03_8007(CpuState *cpu);  /* $03:8007 alias */
RecompReturn bank_03_8007_M0X0(CpuState *cpu);
RecompReturn bank_03_8007_M0X1(CpuState *cpu);
RecompReturn bank_03_8007_M1X0(CpuState *cpu);
RecompReturn bank_03_8007_M1X1(CpuState *cpu);
void bank_03_801C(CpuState *cpu);  /* $03:801C alias */
RecompReturn bank_03_801C_M0X0(CpuState *cpu);
RecompReturn bank_03_801C_M0X1(CpuState *cpu);
RecompReturn bank_03_801C_M1X0(CpuState *cpu);
RecompReturn bank_03_801C_M1X1(CpuState *cpu);
void bank_03_8023(CpuState *cpu);  /* $03:8023 alias */
RecompReturn bank_03_8023_M0X0(CpuState *cpu);
RecompReturn bank_03_8023_M0X1(CpuState *cpu);
RecompReturn bank_03_8023_M1X0(CpuState *cpu);
RecompReturn bank_03_8023_M1X1(CpuState *cpu);
void bank_03_8031(CpuState *cpu);  /* $03:8031 alias */
RecompReturn bank_03_8031_M0X0(CpuState *cpu);
RecompReturn bank_03_8031_M0X1(CpuState *cpu);
RecompReturn bank_03_8031_M1X0(CpuState *cpu);
RecompReturn bank_03_8031_M1X1(CpuState *cpu);
void bank_03_803F(CpuState *cpu);  /* $03:803F alias */
RecompReturn bank_03_803F_M0X0(CpuState *cpu);
RecompReturn bank_03_803F_M0X1(CpuState *cpu);
RecompReturn bank_03_803F_M1X0(CpuState *cpu);
RecompReturn bank_03_803F_M1X1(CpuState *cpu);
void bank_03_8062(CpuState *cpu);  /* $03:8062 alias */
RecompReturn bank_03_8062_M0X0(CpuState *cpu);
RecompReturn bank_03_8062_M0X1(CpuState *cpu);
RecompReturn bank_03_8062_M1X0(CpuState *cpu);
RecompReturn bank_03_8062_M1X1(CpuState *cpu);
void bank_03_820B(CpuState *cpu);  /* $03:820B alias */
RecompReturn bank_03_820B_M0X0(CpuState *cpu);
RecompReturn bank_03_820B_M0X1(CpuState *cpu);
RecompReturn bank_03_820B_M1X0(CpuState *cpu);
RecompReturn bank_03_820B_M1X1(CpuState *cpu);
void bank_03_8362(CpuState *cpu);  /* $03:8362 alias */
RecompReturn bank_03_8362_M0X0(CpuState *cpu);
RecompReturn bank_03_8362_M0X1(CpuState *cpu);
RecompReturn bank_03_8362_M1X0(CpuState *cpu);
RecompReturn bank_03_8362_M1X1(CpuState *cpu);
void bank_03_8374(CpuState *cpu);  /* $03:8374 alias */
RecompReturn bank_03_8374_M0X0(CpuState *cpu);
RecompReturn bank_03_8374_M0X1(CpuState *cpu);
RecompReturn bank_03_8374_M1X0(CpuState *cpu);
RecompReturn bank_03_8374_M1X1(CpuState *cpu);
void bank_03_83F9(CpuState *cpu);  /* $03:83F9 alias */
RecompReturn bank_03_83F9_M0X0(CpuState *cpu);
RecompReturn bank_03_83F9_M0X1(CpuState *cpu);
RecompReturn bank_03_83F9_M1X0(CpuState *cpu);
RecompReturn bank_03_83F9_M1X1(CpuState *cpu);
void bank_03_8B4A(CpuState *cpu);  /* $03:8B4A alias */
RecompReturn bank_03_8B4A_M0X0(CpuState *cpu);
RecompReturn bank_03_8B4A_M0X1(CpuState *cpu);
RecompReturn bank_03_8B4A_M1X0(CpuState *cpu);
RecompReturn bank_03_8B4A_M1X1(CpuState *cpu);
void bank_03_8BD5(CpuState *cpu);  /* $03:8BD5 alias */
RecompReturn bank_03_8BD5_M0X0(CpuState *cpu);
RecompReturn bank_03_8BD5_M0X1(CpuState *cpu);
RecompReturn bank_03_8BD5_M1X0(CpuState *cpu);
RecompReturn bank_03_8BD5_M1X1(CpuState *cpu);
void bank_03_8BF9(CpuState *cpu);  /* $03:8BF9 alias */
RecompReturn bank_03_8BF9_M0X0(CpuState *cpu);
RecompReturn bank_03_8BF9_M0X1(CpuState *cpu);
RecompReturn bank_03_8BF9_M1X0(CpuState *cpu);
RecompReturn bank_03_8BF9_M1X1(CpuState *cpu);
void bank_03_8C4D(CpuState *cpu);  /* $03:8C4D alias */
RecompReturn bank_03_8C4D_M0X0(CpuState *cpu);
RecompReturn bank_03_8C4D_M0X1(CpuState *cpu);
RecompReturn bank_03_8C4D_M1X0(CpuState *cpu);
RecompReturn bank_03_8C4D_M1X1(CpuState *cpu);
void bank_03_8C61(CpuState *cpu);  /* $03:8C61 alias */
RecompReturn bank_03_8C61_M0X0(CpuState *cpu);
RecompReturn bank_03_8C61_M0X1(CpuState *cpu);
RecompReturn bank_03_8C61_M1X0(CpuState *cpu);
RecompReturn bank_03_8C61_M1X1(CpuState *cpu);
void bank_03_8CA3(CpuState *cpu);  /* $03:8CA3 alias */
RecompReturn bank_03_8CA3_M0X0(CpuState *cpu);
RecompReturn bank_03_8CA3_M0X1(CpuState *cpu);
RecompReturn bank_03_8CA3_M1X0(CpuState *cpu);
RecompReturn bank_03_8CA3_M1X1(CpuState *cpu);
void bank_03_8DD2(CpuState *cpu);  /* $03:8DD2 alias */
RecompReturn bank_03_8DD2_M0X0(CpuState *cpu);
RecompReturn bank_03_8DD2_M0X1(CpuState *cpu);
RecompReturn bank_03_8DD2_M1X0(CpuState *cpu);
RecompReturn bank_03_8DD2_M1X1(CpuState *cpu);
void bank_03_8E60(CpuState *cpu);  /* $03:8E60 alias */
RecompReturn bank_03_8E60_M0X0(CpuState *cpu);
RecompReturn bank_03_8E60_M0X1(CpuState *cpu);
RecompReturn bank_03_8E60_M1X0(CpuState *cpu);
RecompReturn bank_03_8E60_M1X1(CpuState *cpu);
void bank_03_8EDD(CpuState *cpu);  /* $03:8EDD alias */
RecompReturn bank_03_8EDD_M0X0(CpuState *cpu);
RecompReturn bank_03_8EDD_M0X1(CpuState *cpu);
RecompReturn bank_03_8EDD_M1X0(CpuState *cpu);
RecompReturn bank_03_8EDD_M1X1(CpuState *cpu);
void bank_03_8F11(CpuState *cpu);  /* $03:8F11 alias */
RecompReturn bank_03_8F11_M0X0(CpuState *cpu);
RecompReturn bank_03_8F11_M0X1(CpuState *cpu);
RecompReturn bank_03_8F11_M1X0(CpuState *cpu);
RecompReturn bank_03_8F11_M1X1(CpuState *cpu);
void bank_03_8FC5(CpuState *cpu);  /* $03:8FC5 alias */
RecompReturn bank_03_8FC5_M0X0(CpuState *cpu);
RecompReturn bank_03_8FC5_M0X1(CpuState *cpu);
RecompReturn bank_03_8FC5_M1X0(CpuState *cpu);
RecompReturn bank_03_8FC5_M1X1(CpuState *cpu);
void bank_03_920B(CpuState *cpu);  /* $03:920B alias */
RecompReturn bank_03_920B_M0X0(CpuState *cpu);
RecompReturn bank_03_920B_M0X1(CpuState *cpu);
RecompReturn bank_03_920B_M1X0(CpuState *cpu);
RecompReturn bank_03_920B_M1X1(CpuState *cpu);
void bank_03_923F(CpuState *cpu);  /* $03:923F alias */
RecompReturn bank_03_923F_M0X0(CpuState *cpu);
RecompReturn bank_03_923F_M0X1(CpuState *cpu);
RecompReturn bank_03_923F_M1X0(CpuState *cpu);
RecompReturn bank_03_923F_M1X1(CpuState *cpu);
void bank_03_9243(CpuState *cpu);  /* $03:9243 alias */
RecompReturn bank_03_9243_M0X0(CpuState *cpu);
RecompReturn bank_03_9243_M0X1(CpuState *cpu);
RecompReturn bank_03_9243_M1X0(CpuState *cpu);
RecompReturn bank_03_9243_M1X1(CpuState *cpu);
void bank_03_9268(CpuState *cpu);  /* $03:9268 alias */
RecompReturn bank_03_9268_M0X0(CpuState *cpu);
RecompReturn bank_03_9268_M0X1(CpuState *cpu);
RecompReturn bank_03_9268_M1X0(CpuState *cpu);
RecompReturn bank_03_9268_M1X1(CpuState *cpu);
void bank_03_92AA(CpuState *cpu);  /* $03:92AA alias */
RecompReturn bank_03_92AA_M0X0(CpuState *cpu);
RecompReturn bank_03_92AA_M0X1(CpuState *cpu);
RecompReturn bank_03_92AA_M1X0(CpuState *cpu);
RecompReturn bank_03_92AA_M1X1(CpuState *cpu);
void bank_03_9327(CpuState *cpu);  /* $03:9327 alias */
RecompReturn bank_03_9327_M0X0(CpuState *cpu);
RecompReturn bank_03_9327_M0X1(CpuState *cpu);
RecompReturn bank_03_9327_M1X0(CpuState *cpu);
RecompReturn bank_03_9327_M1X1(CpuState *cpu);
void bank_03_9362(CpuState *cpu);  /* $03:9362 alias */
RecompReturn bank_03_9362_M0X0(CpuState *cpu);
RecompReturn bank_03_9362_M0X1(CpuState *cpu);
RecompReturn bank_03_9362_M1X0(CpuState *cpu);
RecompReturn bank_03_9362_M1X1(CpuState *cpu);
void bank_03_939E(CpuState *cpu);  /* $03:939E alias */
RecompReturn bank_03_939E_M0X0(CpuState *cpu);
RecompReturn bank_03_939E_M0X1(CpuState *cpu);
RecompReturn bank_03_939E_M1X0(CpuState *cpu);
RecompReturn bank_03_939E_M1X1(CpuState *cpu);
void bank_03_9417(CpuState *cpu);  /* $03:9417 alias */
RecompReturn bank_03_9417_M0X0(CpuState *cpu);
RecompReturn bank_03_9417_M0X1(CpuState *cpu);
RecompReturn bank_03_9417_M1X0(CpuState *cpu);
RecompReturn bank_03_9417_M1X1(CpuState *cpu);
void bank_03_9680(CpuState *cpu);  /* $03:9680 alias */
RecompReturn bank_03_9680_M0X0(CpuState *cpu);
RecompReturn bank_03_9680_M0X1(CpuState *cpu);
RecompReturn bank_03_9680_M1X0(CpuState *cpu);
RecompReturn bank_03_9680_M1X1(CpuState *cpu);
void bank_03_9717(CpuState *cpu);  /* $03:9717 alias */
RecompReturn bank_03_9717_M0X0(CpuState *cpu);
RecompReturn bank_03_9717_M0X1(CpuState *cpu);
RecompReturn bank_03_9717_M1X0(CpuState *cpu);
RecompReturn bank_03_9717_M1X1(CpuState *cpu);
void bank_03_98EE(CpuState *cpu);  /* $03:98EE alias */
RecompReturn bank_03_98EE_M0X0(CpuState *cpu);
RecompReturn bank_03_98EE_M0X1(CpuState *cpu);
RecompReturn bank_03_98EE_M1X0(CpuState *cpu);
RecompReturn bank_03_98EE_M1X1(CpuState *cpu);
void bank_03_992A(CpuState *cpu);  /* $03:992A alias */
RecompReturn bank_03_992A_M0X0(CpuState *cpu);
RecompReturn bank_03_992A_M0X1(CpuState *cpu);
RecompReturn bank_03_992A_M1X0(CpuState *cpu);
RecompReturn bank_03_992A_M1X1(CpuState *cpu);

/* Hand-written non-recompiled bodies still declared here.
 * These are not produced by the v2 emit pipeline but are
 * referenced by recompiled code via funcs.h.
 */
void ResetSpritesFunc(int wh);
void RunOneFrameOfGame_Internal(void);

/* Watchdog hook called at every block label. Implemented in
 * snesrecomp/runner/src/common_cpu_infra.c.
 */
void WatchdogCheck(void);
